### ISSUE TITLE
Juman++ v2 TODO list

### ISSUE THREAD

**Issue by eiennohito** [ku-nlp/jumanpp#8]
Juman++ is being rewritten right now with the following goals:

* Make analysis faster
* Make it possible to use Juman++ as a library
  * No global mutable state
  * Well-defined thread safety
* Make it possible to use Juman++ with dictionaries/POS sets other than Jumandic

The code is available in [v2](https://github.com/ku-nlp/jumanpp/tree/v2) branch. It is expected to have at least 6x analysis speed compared to the current version of Juman++.

The main objective is to have feature parity with the current version of Juman++ (dictionary format will not be compatible though).

## Current code TODO list

- [x] Number UNK handling (#12)
- [x] Onomatopeia UNK handling (#9)
- [x] Dictionary-based surface normalization (#11)
- [x] Morph output format
- [x] Model serialization logic (perceptron)
- [x] Training binary
- [x] RNN import/adaptation logic
- [x] Correctly handle surface length (#13)
- [x] Output correct Jumandic POS ids
- [x] Lattice output format
- [x] Static feature application code generation
- [x] RNN can handle multiple fields (#42)

**Comment by eiennohito** [comment]
This is done
